# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Community Laboratory for AI Research at the Intersection with Physics (CLARIPHY)
shorttitle: CLARIPHY
email: Peter.Elmer@cern.ch
description: >- # this means to ignore newlines until "baseurl:"
  Community Laboratory for AI Research at the Intersection with Physics (CLARIPHY)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://clariphy.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: clariphy
github_username: clariphy 
excerpt_separator: <!--more-->

footer:
  copyright_text: 'CLARIPHY is an informal collaboration of researchers from a number of universities and national laboratories. Any opinions, findings, conclusions or recommendations expressed in this material are those of the authors and do not necessarily reflect the views of their institutions or any entities funding their work.'

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
#  - jekyll-environment-variables
# seems to cause problems currently (March 2019)
#  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # Added
  - _cache
  - _scripts
  - _sources
  - bin
  - .github

sass:
  sass_dir: _sass
  style: compact # possible values: nested expanded compact compressed

indico:
  url: https://indico.fnal.gov
  ids:
    topical: 1253
