name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: master
  schedule:
  - cron: "0 0 * * *"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Restore publication cache
      uses: actions/cache@v4
      with:
        path: _cache
        key: ${{ runner.os }}-_cache-${{ hashFiles('_data/publications/*.yml') }}

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Check RuboCop
      run: bundle exec rake rubocop || true

    - name: Build the site
      run: bundle exec rake build
      env:
        JEKYLL_ENV: production

    - name: Check for issues
      run: bundle exec rake checkonly || true

    - name: Upload artifact
      if: github.ref == 'refs/heads/master' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule')
      uses: actions/upload-pages-artifact@v3
      with:
        path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule')
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
